Geopy 1451
MiraGeoscience/simpeg-drivers pull request #12
Opened 2024-04-15 12:44 UTC by domfournier

2024-04-17 19:46 UTC, benk-mira requested changes
Wow, that was a whopper!  Looks really great overall!  I caught some spelling mistakes, maybe try to run a spellchecker on the .py files? Also caught several errors in the figure captions, so maybe have a closer look when doing round 2.

I also have a couple of general comments:
1. More images of ui.  Break into ui groups and try to reference more regularily in the text.
2. I think the tutorials would have been better written up in terms of an individual inversion first, and then a joint, rather than mashing the topics together.

2024-04-17 19:46 UTC, benk-mira commented on docs/case_study/mesh_design.py
> +# This section provides details about the mesh creation for the individual inversions using the `Octree Mesh Creation` routine from [Mirageoscience\geoapps](https://mirageoscience-octree-creation-app
.. Or I guess we could just point to the octree-creation-app docs for single mesh parameters, and just focus on the joint details here.  Then you'd just have to have a sentence at the top that says: "For individual inversions, the mesh creation process is already well documented in _link_.  Therefore we will restrict the discussion here to details regarding joint mesh blah blah blah."

2024-04-17 19:46 UTC, benk-mira commented on docs/case_study/unconstrained_inversion.py
> +# (Bottom) Horizontal slice for (left) the smooth and (right) L1-norm density contrast models. The outline of the inferred ore shell is shown in gray for reference.
reference iterations numbers in caption

2024-04-17 19:46 UTC, benk-mira commented on docs/case_study/unconstrained_inversion.py
> +# (Right) Vertical NS section through the recovered smooth resistivity model.
no shell

2024-04-22 17:34 UTC, domfournier commented on docs/inversion/data_misfit.py
> +#  - Numerically noise introduced by $F(\mathbf{m})$ from our ability to accurately simulate the physics (discretization, interpolation, etc.)
Done

2024-04-22 17:34 UTC, domfournier commented on docs/inversion/data_misfit.py
> +# It measures the sum of **weighted residual** between observed ($\mathbf{d}^{obs}$) and predicted ($\mathbf{d}^{pre}$) data. In matrix form, this least-square measure can be written as
Done

2024-04-22 17:35 UTC, domfournier commented on docs/inversion/data_misfit.py
> +# As mentioned in the [Data Misfit](#Data-Misfit) section, we want to assign **data uncertainties** that reflect our ability to replicate the observed data, within an acceptable level. While many str
DOne

2024-04-22 18:08 UTC, domfournier commented on docs/inversion/regularization.py
> +# A second set of terms can be added to the regularization function to apply constraints on the model gradients, or roughness of the solution. Following the notation used in {cite:p}`LiOldenburg1998`
Agreed. Done

2024-04-22 18:09 UTC, domfournier commented on docs/inversion/regularization.py
> +# While often referred to as an "unconstrained inversion", one could argue that the conventional model norm regularizations do still incorporate some degree of geological information, at least in the
Done

2024-04-22 18:10 UTC, domfournier commented on docs/inversion/regularization.py
> +# where $\mathbf{G}_x$ is a finite different operator that measures the gradient of the model $\mathbf{m}$ along one of the Cartesian directions (`x` for Easting). This function keeps the model "smoo
Done

2024-04-22 18:29 UTC, domfournier commented on docs/inversion/regularization.py
> +# For all SimPEG inversions, dimensionality scaling is applied directly by the program, allowing the default state to be all 1s for simplicity.
Add notes

2024-04-22 18:30 UTC, domfournier commented on docs/inversion/regularization.py
> +# Here the superscript $(k)$ denotes the inversion iteration number. This is also unknown as an iterative re-weighted least-squares (IRLS) method. For more details on the implementation refer to {cit
Done

2024-04-22 18:30 UTC, domfournier commented on docs/inversion/regularization.py
> +# No smoothness constraints were used ($\alpha_x,y,z = 0$).
Done

2024-04-22 18:34 UTC, domfournier commented on docs/inversion/regularization.py
> +# ![smallness_setup](./images/smallness_norm_setup.png)
Moved comment below image.

2024-04-22 18:34 UTC, domfournier commented on docs/inversion/regularization.py
> +# ![smoothness_setup](./images/smoothness_norm_setup.png)
Done

2024-04-22 18:39 UTC, domfournier commented on docs/inversion/joint_inversion.py
> +# This section introduces the methodolgy to invert multiple datasets jointly.
Done

2024-04-22 18:40 UTC, domfournier commented on docs/inversion/joint_inversion.py
> +# For example, a magnetotelluric survey is mostly sensitive to deep structures but can still be affected by local changes in resistivity near the sensor locations. A ground direct-current survey on t
Done

2024-04-22 18:41 UTC, domfournier commented on docs/inversion/joint_inversion.py
> +# The joint survey inversion user requires a list of standalone inversion groups as input.
I will deal with this when we revamp the tutorial

2024-04-22 18:42 UTC, domfournier commented on docs/inversion/joint_inversion.py
> +# The `cross-gradient` regularization was first introduced by {cite:p}`gallardo2003` to constrain electrical resistivity and seismic velocity inversions, but the same strategy applies to any physical
Done

2024-04-22 18:43 UTC, domfournier commented on docs/inversion/joint_inversion.py
> +# and so on. Each term has a scaling parameter ($\alpha$) to control the importance of specific cross-gradient terms.
Yep, later

2024-04-22 18:54 UTC, domfournier commented on docs/case_study/mesh_design.py
> +# This section provides details about the mesh creation for the individual inversions using the `Octree Mesh Creation` routine from [Mirageoscience\geoapps](https://mirageoscience-octree-creation-app
Good point

2024-04-22 19:02 UTC, domfournier commented on docs/case_study/mesh_design.py
> +# This section provides details about the mesh creation for the individual inversions using the `Octree Mesh Creation` routine from [Mirageoscience\geoapps](https://mirageoscience-octree-creation-app
Make sense

2024-04-22 19:06 UTC, domfournier commented on docs/case_study/mesh_design.py
> +# - Radial: Add concentric spherical shells of cells around points. It is used for numerical accuracy near receiver poles (DC) and dipoles (EM).
I will add reference to octree-docs, and push this one under the rug for now.

2024-04-24 19:28 UTC, merged